FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04
ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /base
RUN apt-get update && apt-get install -y python3 python3-pip cmake wget llvm
RUN apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev
RUN pip3 install numpy==1.16.1
RUN pip3 install opencv-python
RUN pip3 install configparser==5.0.2
RUN pip3 install pillow==9.0.0
RUN pip3 install six==1.16.0
RUN pip3 install future==0.18.2
RUN pip3 install python-multipart
RUN pip3 install uvicorn==0.14.0 fastapi==0.65.2
RUN pip3 install requests
RUN pip3 install vietocr unidecode torch
RUN pip3 install torchvision pyyaml pillow
CMD sh start_service.sh

